### PR TITLE
Update dri control to not force a specific version

### PR DESCRIPTION
**Pull request by Gymxo**
This always seems to mess stuff up :/

### CODE REVIEW

**Comment by TheRealKeto** [comment]
You should also update the version of the Makefile, so that it appears as an upgrade on package managers.

**Comment by Diatrus** [comment]
Not only is this wrong but dri isnt even used now.

**Comment by Gymxo** [comment]
Alright

**Comment by Gymxo** [comment]
Just trying to find out what’s wrong with dummy driver

**Pull request closed without merging**
