### PR TITLE
Add docbook-xsl

### PR DESCRIPTION
**Pull request by Cryptiiiic**
**Add docbook**
_Todo:_ 
* Update Makefile to check for procursus docbook
* Loop/Array most of the downloads/calls
* Maybe rename it to docbook-xsl? idk

### CODE REVIEW

**Comment by CRKatri** [comment]
You gotta debianize this

**Comment by Cryptiiiic** [comment]
@CRKatri this is a direct copy past from homebrew, what’s needed to debianize it

**Comment by CRKatri** [comment]
Look at how Debian packages the docbook* packages and copy that

**Comment by Diatrus** [comment]
Closed by aa1598a5996b82d89c6c75cee3f27e25d7b92df0

**Pull request closed without merging**
