### PR TITLE
meson: Update to 0.61.1

### PR DESCRIPTION
**Pull request by TheRealKeto**
This PR updates ``meson`` to the latest released version, 0.59.2 Other changes, such as a better control file description and the addition of ``ninja`` as a dependency in the Makefile, were also made.

### CODE REVIEW

**Comment by DaOfficialRolex** [comment]
Just to let you know that meson 0.59.0 was released.

**Comment by TheRealKeto** [comment]
Already updated; despite it being a RC, it works out of the box without issues.

**Comment by TheRealKeto** [comment]
Updated meson to the latest release.

**Review by CRKatri — CHANGES_REQUESTED** [review]
Please update to  0.60.3

**Comment by TheRealKeto** [comment]
@CRKatri Everything's been updated to reflect the latest changes.

**Review by CRKatri — APPROVED** [review]

**Pull request merged**
