### PR TITLE
Update apple-cmds to their latest versions

### PR DESCRIPTION
**Pull request by asdfugil**
Hi,

This PR updates apple-cmds to their respective latest versions.
Multiple binaries are also added, the specifics can be found in the commit messages.
This PR is subtly incompatible with existing build bases, in order to use
an existing build base to build this PR, you must
 - Delete `$(BUILD_BASE)$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/include/sys/*proc*.h`
 - Delete all downloaded headers in build base

----
Changes from #1147:
- Cleaned commit history, it is all too messy
- Remove `kpgo`, `gcore` and `sa` since they do not work on RELEASE kernels.
- Header download now uses `DOWNLOAD_FILES`
```
 Makefile                                                                       | 121 ++++++++++++++++++------
 build_info/adv-cmds.control                                                    |   2 +-
 build_info/network-cmds.control                                                |   2 +-
 build_misc/PrivateFrameworks/CoreSymbolication.framework/CoreSymbolication.tbd | 458 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 build_misc/PrivateFrameworks/ktrace.framework/ktrace.tbd                       | 282 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 build_misc/entitlements/fs_usage.plist                                         |  14 +++
 build_misc/entitlements/login.plist                                            |  13 +++
 build_misc/entitlements/lsmp-legacy.xml                                        |  16 ++++
 build_misc/entitlements/passwd.plist                                           |  18 ++++
 build_misc/entitlements/vm_purgeable_stat.plist                                |  13 +++
 makefiles/adv-cmds.mk                                                          |  18 ++--
 makefiles/basic-cmds.mk                                                        |   8 +-
 makefiles/bootstrap-cmds.mk                                                    |   8 +-
 makefiles/diskdev-cmds.mk                                                      |   6 +-
 makefiles/doc-cmds.mk                                                          |   2 +-
 makefiles/file-cmds.mk                                                         |  28 +++---
 makefiles/network-cmds.mk                                                      | 124 ++++++++++--------------
 makefiles/shell-cmds.mk                                                        |  25 +++--
 makefiles/system-cmds.mk                                                       |  74 ++++++++++-----
 makefiles/text-cmds.mk                                                         |  17 +++-
 20 files changed, 1079 insertions(+), 170 deletions(-)
 ```
 
### All Submissions

* [x] Have you made sure there aren't any other open [Pull Requests](https://github.com/ProcursusTeam/Procursus/pulls) for the same update/change?
* [ ] This Pull Request doesn't contain any package additions; it's a small change (e.g README change)

### Package Additions/Updates

* [x] Have you confirmed this builds & works as intended on an iOS device (if applicable)?
* [ ] Have you confirmed this builds & works as intended on a macOS device (if applicable)?

Nick Chan

### CODE REVIEW

**Comment by asdfugil** [comment]
Changes in version 3 (version 2 is above)
- Dropped system-cmds hack, and downgraded system-cmds to compatible versions
- Update cmds to macOS ventura equivalents where possible
- Added new binaries in developer-cmds
- Added dirs_cleaner binary in file-cmds
- Dropped rmt binary in file-cmds for iOS 13 and above, because it has been removed upstream

```
 Makefile                                                                                      | 148 ++++++++++++++++++++++++++----------
 build_info/adv-cmds.control                                                                   |   2 +-
 build_info/network-cmds.control                                                               |   2 +-
 build_misc/PrivateFrameworks/CoreSymbolication.framework/CoreSymbolication.tbd                | 458 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 build_misc/PrivateFrameworks/ktrace.framework/ktrace.tbd                                      | 282 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 build_misc/entitlements/fs_usage.plist                                                        |  14 ++++
 build_misc/entitlements/login.plist                                                           |  13 ++++
 build_misc/entitlements/lsmp-legacy.xml                                                       |  16 ++++
 build_misc/entitlements/passwd.plist                                                          |  18 +++++
 build_misc/entitlements/vm_purgeable_stat.plist                                               |  13 ++++
 build_patch/developer-cmds/0001-Add-missing-function-declarations.patch                       |  50 +++++++++++++
 build_patch/system-cmds-ios15/0001-jailbreak-add-code-to-use-jailbreakd-services-where-.patch |  71 ++++++++++++++++++
 build_patch/system-cmds-ios15/0001-system_cmds-shutdown-may-not-work.patch                    |  80 ++++++++++++++++++++
 build_patch/system-cmds-ios15/0002-jailbreak-add-code-to-use-jailbreakd-services-where-.patch |  71 ++++++++++++++++++
 build_patch/system-cmds-ios15/0002-login-patch-setuid-where-needed.patch                      |  38 ++++++++++
 build_patch/system-cmds-ios15/0003-login-patch-setuid-where-needed.patch                      |  38 ++++++++++
 build_patch/system-cmds-ios15/0003-reboot-always-attempt-to-platformize-with-jailbreakd.patch |  37 +++++++++
 build_patch/system-cmds-ios15/0004-fixup-system_cmds-shutdown-may-not-work.patch              |  25 +++++++
 build_patch/system-cmds-ios15/0004-reboot-always-attempt-to-platformize-with-jailbreakd.patch |  37 +++++++++
 build_patch/system-cmds-ios15/bettercrypt.diff                                                |  50 +++++++++++++
 build_patch/system-cmds/ios.diff                                                              |   2 +-
 makefiles/adv-cmds.mk                                                                         |  18 +++--
 makefiles/basic-cmds.mk                                                                       |   8 +-
 makefiles/bootstrap-cmds.mk                                                                   |   8 +-
 makefiles/developer-cmds.mk                                                                   |  11 ++-
 makefiles/diskdev-cmds.mk                                                                     |  12 ++-
 makefiles/doc-cmds.mk                                                                         |   2 +-
 makefiles/file-cmds.mk                                                                        |  31 +++++---
 makefiles/misc-cmds.mk                                                                        |   6 +-
 makefiles/network-cmds.mk                                                                     | 126 +++++++++++++------------------
 makefiles/shell-cmds.mk                                                                       |  25 ++++---
 makefiles/system-cmds.mk                                                                      |  84 +++++++++++++++------
 makefiles/text-cmds.mk                                                                        |  17 ++++-
 33 files changed, 1622 insertions(+), 191 deletions(-)
 ```

**Comment by asdfugil** [comment]
Changes in version 4:
- Do not download `sys/mtio.h`, as it is an obsolete header
- Remove binaries not shipped with macOS
- Bump system-cmds version for iOS 12
- Dropped anything jailbreakd related
- Dropped developer-cmds patch, instead fix the compiler flags

**Comment by CRKatri** [comment]
What is the current status of this? Is it ready for review?

**Comment by asdfugil** [comment]
> What is the current status of this? Is it ready for review?

it is ready for review, please note that due to the header changes, it is not compatible with an existing build_base

**Comment by asdfugil** [comment]
you will also need xcode 14

**Review by CRKatri — APPROVED** [review]
Thank you!
Sorry for taking so long to review 🙃

**Pull request merged**
