### PR TITLE
Add opendircolors

### PR DESCRIPTION
**Pull request by CRKatri**
This is untested because Procursus doesn't support FreeBSD, and is only on `darwin-*` because it is useless on iOS because you only have a GNU userland, unlike MacOS which comes with a FreeBSD userland.

### CODE REVIEW

**Comment by Diatrus** [comment]
I want to replace the GNU userland on iOS properly sometime so we’ll keep this held right now.

**Comment by CRKatri** [comment]
Should now support iOS, although usefulness is pretty much zero, until a BSD userland is available.

**Comment by demhademha** [comment]
I think the section should be **utilities**

**Comment by CRKatri** [comment]
When you say you want a BSD userland do you want to use macOS' from opensource.apple.com? Or porting it from (Free|Net|Open)BSD which I don't like because apple did most the work and has some of it's own features.

**Pull request closed without merging**
