### PR TITLE
fix libiosexec

### PR DESCRIPTION
**Pull request by sunflsks**
`all` makes the static and dynamic libraries anyway, which is what is needed

### CODE REVIEW

**Review by asdfugil — COMMENTED** [review]
this library can't be found by ld
```
gcc  -DHAVE_CONFIG_H -DSHELL  -I/home/nick/procursus_utils/build/build_work/iphoneos-arm64/1700/bash -I.. -DMACOSX  -g man2html.o -o man2html -ldl -L/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700//usr/lib -liosexec
/usr/bin/ld: 找不到 -liosexec
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:80: man2html] Error 1
make[1]: *** [Makefile:753: support/man2html] Error 1
```

**Comment by CRKatri** [comment]
Good, cause that of compiling for the host not the target.

**Comment by CRKatri** [comment]
Why are you using gcc to compile for iOS instead of clang? I didn’t even know gcc supported arm64 Mach-o

**Comment by CRKatri** [comment]
Also, update this to use the `install` target as well.

**Comment by asdfugil** [comment]
> Why are you using gcc to compile for iOS instead of clang? I didn’t even know gcc supported arm64 Mach-o

a bug in bash makefile
actually you fixed that in freebsd pr
https://github.com/ProcursusTeam/Procursus/pull/705/commits/00e0002852ed48c95edb0f186e5f254fae597b25

**Comment by asdfugil** [comment]
that said using clang does not help
```
clang  -DHAVE_CONFIG_H -DSHELL  -I/home/nick/procursus_utils/build/build_work/iphoneos-arm64/1700/bash -I.. -DMACOSX  -g man2html.o -o man2html -ldl -L/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700//usr/lib -liosexec
/bin/sh ./support/mkversion.sh -b -S . -s release -d 5.1 -o newversion.h \
        && mv newversion.h version.h
rm -f shell.o
rm -f eval.o
aarch64-apple-darwin-clang  -DPROGRAM='"bash"' -DCONF_HOSTTYPE='"aarch64"' -DCONF_OSTYPE='"darwin"' -DCONF_MACHTYPE='"aarch64-apple-darwin"' -DCONF_VENDOR='"apple"' -DLOCALEDIR='"/usr/share/locale"' -DPACKAGE='"bash"' -DSHELL -DHAVE_CONFIG_H -DMACOSX   -I. -I/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/lib/include -I. -I./include -I./lib   -O2 -arch arm64 -miphoneos-version-min=14.0 -isysroot /home/nick/procursus_utils/SDKs/iPhoneOS14.4.sdk -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/include -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/local/include -Wno-error-implicit-function-declaration -O2 -arch arm64 -isysroot /home/nick/procursus_utils/SDKs/iPhoneOS14.4.sdk -miphoneos-version-min=14.0 -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/include -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/local/include -F/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/System/Library/Frameworks -F/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/Library/Frameworks -DSSH_SOURCE_BASHRC  -c shell.c
aarch64-apple-darwin-clang  -DPROGRAM='"bash"' -DCONF_HOSTTYPE='"aarch64"' -DCONF_OSTYPE='"darwin"' -DCONF_MACHTYPE='"aarch64-apple-darwin"' -DCONF_VENDOR='"apple"' -DLOCALEDIR='"/usr/share/locale"' -DPACKAGE='"bash"' -DSHELL -DHAVE_CONFIG_H -DMACOSX   -I. -I/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/lib/include -I. -I./include -I./lib   -O2 -arch arm64 -miphoneos-version-min=14.0 -isysroot /home/nick/procursus_utils/SDKs/iPhoneOS14.4.sdk -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/include -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/local/include -Wno-error-implicit-function-declaration -O2 -arch arm64 -isysroot /home/nick/procursus_utils/SDKs/iPhoneOS14.4.sdk -miphoneos-version-min=14.0 -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/include -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/local/include -F/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/System/Library/Frameworks -F/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/Library/Frameworks -DSSH_SOURCE_BASHRC  -c eval.c
rm -f execute_cmd.o
aarch64-apple-darwin-clang  -DPROGRAM='"bash"' -DCONF_HOSTTYPE='"aarch64"' -DCONF_OSTYPE='"darwin"' -DCONF_MACHTYPE='"aarch64-apple-darwin"' -DCONF_VENDOR='"apple"' -DLOCALEDIR='"/usr/share/locale"' -DPACKAGE='"bash"' -DSHELL -DHAVE_CONFIG_H -DMACOSX   -I. -I/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/lib/include -I. -I./include -I./lib   -O2 -arch arm64 -miphoneos-version-min=14.0 -isysroot /home/nick/procursus_utils/SDKs/iPhoneOS14.4.sdk -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/include -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/local/include -Wno-error-implicit-function-declaration -O2 -arch arm64 -isysroot /home/nick/procursus_utils/SDKs/iPhoneOS14.4.sdk -miphoneos-version-min=14.0 -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/include -isystem /home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/usr/local/include -F/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/System/Library/Frameworks -F/home/nick/procursus_utils/build/build_base/iphoneos-arm64/1700/Library/Frameworks -DSSH_SOURCE_BASHRC  -c execute_cmd.c
/usr/bin/ld: 找不到 -liosexec
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:80: man2html] Error 1
make[1]: *** [Makefile:753: support/man2html] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by CRKatri** [comment]
That is a helper program being compiled for the host, it shouldn't be linking libiosexec at all.

**Pull request merged**
