### PR TITLE
Add dropbear

### PR DESCRIPTION
**Pull request by CRKatri**
Requires #184 and #186

### CODE REVIEW

**Comment by Diatrus** [comment]
Please rebase to as2.

**Comment by Diatrus** [comment]
Change the stuff to fit with as2. Including paths and such.

**Comment by Diatrus** [comment]
sysconfdir should be MEMO_PREFIX/etc not just /etc. This is self contained.

**Comment by Diatrus** [comment]
Still scripts :P

**Comment by Diatrus** [comment]
Just realized the install names of tomato and tomcrypt are both in /usr/local???? Possible to also fix that in this PR?

**Comment by CRKatri** [comment]
Should be fixed now

**Pull request merged**
