### PR TITLE
Added bash-completion for those who still use bash

### PR DESCRIPTION
**Pull request by DaOfficialRolex**

### CODE REVIEW

**Comment by brennanleblanc0** [comment]
i feel personally attacked by this PR name

**Review by demhademha — CHANGES_REQUESTED** [review]
It should be:
		--prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)
**not**
		--prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX) \

**Comment by DaOfficialRolex** [comment]
> It should be:
> --prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)
> **not**
> --prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX) \

This change doesn't really effect anything. It compiles and packages everything in the same way.

**Comment by Diatrus** [comment]
> > It should be:
> > --prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)
> > **not**
> > --prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX) \
> 
> This change doesn't really effect anything. It compiles and packages everything in the same way.

It definitely does affect. The first make command doesn't run due to it and is passed to configure lol

**Comment by DaOfficialRolex** [comment]
> > > It should be:
> > > --prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)
> > > **not**
> > > --prefix=$(MEMO_PREFIX)$(MEMO_SUB_PREFIX) \
> > 
> > 
> > This change doesn't really effect anything. It compiles and packages everything in the same way.
> 
> It definitely does affect. The first make command doesn't run due to it and is passed to configure lol

Got it will push the change then.

**Pull request merged**
