### PR TITLE
Add new_keyring.sh

### PR DESCRIPTION
**Pull request by CRKatri**

### CODE REVIEW

**Comment by TheRealKeto** [comment]
Keyrings should be handled like tarballs; good job on the template. However, I'd add the Author field to the control file.

**Comment by CRKatri** [comment]
Wdym like tarballs? If you mean download them, then no, that is insecure and currently all keyring packages have them tracked in git. Also, PGP keys don’t have authors.

**Comment by TheRealKeto** [comment]
I don't know how it's insecure. We're not a server that stores PGP keys and revoke certificates; each individual who would like to have their keyring in the build system should make their package download the signature from a different source, just like we download a tarball from a mirror or Github. We don't need to keep track of these files ourselves!

**Comment by Diatrus** [comment]
We should keep track of keys ourselves.

**Review by TheRealKeto — APPROVED** [review]
Add every project tarball, then. Let's not run the risk that those might be insecure too... zzz...

**Comment by Diatrus** [comment]
There’s a big difference between a code tarball and a gpg key

**Pull request merged**
