### PR TITLE
Add Kext tools

### PR DESCRIPTION
**Pull request by asdfugil**
### All Submissions

* [x] Have you made sure there aren't any other open [Pull Requests](https://github.com/ProcursusTeam/Procursus/pulls) for the same update/change?
* [ ] This Pull Request doesn't contain any package additions; it's a small change (e.g README change)

### Package Additions/Updates

* [x] Have you confirmed this builds & works as intended on an iOS device (if applicable)?
* [ ] Have you confirmed this builds & works as intended on a macOS device (if applicable)?
 kextstat and mkextunpack works

kextstat and mkextunpack works

### CODE REVIEW

**Comment by asdfugil** [comment]
- sys/cdefs.h are no longer overriden
- some patches made in here is not required when building on iOS and macOS, but needed when on Linux (didn't test FreeBSD)

**Comment by asdfugil** [comment]
The iOS kernel appears to block kext from unloading, but does not appear to block kext loading.

**Comment by asdfugil** [comment]
At least from [this](https://github.com/apple-oss-distributions/xnu/blob/main/libkern/c%2B%2B/OSKext.cpp) file anyways

**Comment by CRKatri** [comment]
Why did you exclude `kextutil(8)`?

**Review by CRKatri — APPROVED** [review]

**Comment by asdfugil** [comment]
It requires security.c, which requires some macOS only `Security.framework` function. Same goes for kextd.

**Comment by asdfugil** [comment]
...and some implementation kextd is needed to load dexts.

**Pull request merged**
