### PR TITLE
Add libarchive

### PR DESCRIPTION
**Pull request by CRKatri**
(Currently broken)

### CODE REVIEW

**Comment by Diatrus** [comment]
Why would you add zlib when it's included in the iOS sdk?

**Comment by CRKatri** [comment]
I was unaware of that. I'll remove it.

**Comment by luxxxxy** [comment]
@Diatrus is it a symlink?

**Comment by Diatrus** [comment]
@luxxxxy no it's just libz.

**Comment by Diatrus** [comment]
As a matter of fact, libarchive is a part of the iOS sdk. If there's no valid reason for this to overshadow the iOS-included libarchive, then I see no reason to merge this.

**Comment by CRKatri** [comment]
It provides bsdtar and bsdcat, which have some functionality that gnu tar and cat don't provide.

**Comment by Diatrus** [comment]
Alright, make sure it includes support for every single compression Procursus provides (including xar) and test on device, then I'll merge.

**Comment by CRKatri** [comment]
Thank you! I was having some trouble figuring that out.

**Comment by Diatrus** [comment]
No problem at all

**Pull request merged**
