### PR TITLE
Add tapi command

### PR DESCRIPTION
**Pull request by sunflsks**
Adds the `tapi` command and reorganizes package files.

If merged, #781 should probably be closed

### CODE REVIEW

**Comment by CRKatri** [comment]
You may want to soversion the libtapi package, unless there's a reason @Diatrus didn't when he added it.

**Comment by Diatrus** [comment]
@CRKatri i didn’t because it didn’t. Occasionally there is a package without an sover and that’s ok.

**Comment by CRKatri** [comment]
It does though, `8svn` iirc, but I believe it just borrows it from the `llvm` that it compiles against. [`tapi-1200.0.23`](https://opensource.apple.com/release/developer-tools-120.html) may have an ABI change so it may be necessary to setup a so version in that case, but if Apple says "coming soon", who knows when that is.

**Comment by Diatrus** [comment]
@CRKatri between versions 1000 and 1100 there was no abi change, so I expect the same here.

**Pull request merged**
