### PR TITLE
add tcsh and rc

### PR DESCRIPTION
**Pull request by sunflsks**
I've also done ksh, but i've had to do some horrendous patching of the `meson.build`, so I'm not going to include that here. I have it on a seperate branch on my fork. rc is fully functional on my iOS 14 device. tcsh is unable to access the termcap database, so that needs to be fixed as well.

### CODE REVIEW

**Comment by sunflsks** [comment]
The problem with `tcsh` not being able to find the terminfo database does not seem to be in the way I've compiled it, but rather due to the fact that there is something wrong with the terminfo database, since `tcsh` from other repositories (notably MCApollo) seem to have the same issue. Therefore, I'm marking this as ready to review.

**Comment by Diatrus** [comment]
@sunflsks does it successfully link with libncursesw from Procursus? or does it link the one from the macOS sdk?

**Comment by sunflsks** [comment]
I just ran `otool -L` on the tcsh binary, and it turns out it's linking to `libncurses.5.4.dylib`, which is probably the ncurses from my macOS machine.

**Comment by sunflsks** [comment]
This commit fixes the issue with tcsh so it should be ready to merge

**Pull request merged**
