### PR TITLE
add jtool2

### PR DESCRIPTION
**Pull request by sunflsks**

### CODE REVIEW

**Comment by CRKatri** [comment]
Let me know when this is open source and I'll approve, but I don't think we should distribute binaries that we don't build.

**Comment by sunflsks** [comment]
Yeah, I was thinking that that might be a problem. I'll close this now.

**Comment by demhademha** [comment]
In the words of Hayden regarding this:
`it can i guess`

**Comment by Diatrus** [comment]
Wait till I can test on m1

**Pull request merged**
