### PR TITLE
Add Tigervnc to Procursus 

### PR DESCRIPTION
**Pull request by Gymxo**

### CODE REVIEW

**Review by legit100LP — APPROVED** [review]

**Comment by Gymxo** [comment]
Hopefully finish this by today

**Comment by Gymxo** [comment]
Apparently, these variables may do something
QT_X11_NO_MITSHM=1
_X11_NO_MITSHM=1
_MITSHM=0

**Comment by Gymxo** [comment]
I'll disable mit-shm by default if building for ios.

**Comment by Gymxo** [comment]
We do a little trolling

**Comment by Gymxo** [comment]
The commits mean nothing 💯

**Comment by m1stadev** [comment]
thank god for ‘Squash and merge’

**Comment by Gymxo** [comment]
God I just want this pr to be over with

**Comment by Gymxo** [comment]
It’s been almost 2 months by now

**Comment by Diatrus** [comment]
@Gymxo fix the thing i said then

**Comment by Gymxo** [comment]
Just got home I’ll do it right now

**Comment by Gymxo** [comment]
dunny

**Pull request merged**
