### PR TITLE
Updated calc to 2.13.0.1.

### PR DESCRIPTION
**Pull request by DaOfficialRolex**

### CODE REVIEW

**Review by asdfugil — APPROVED** [review]

**Review by Gymxo — APPROVED** [review]

**Comment by asdfugil** [comment]
wait actually

**Review by asdfugil — CHANGES_REQUESTED** [review]
Please move it to the `Math` section

**Comment by Gymxo** [comment]
True true

**Review by asdfugil — APPROVED** [review]

**Comment by Cryptiiiic** [comment]
Why math, its a utility, creating a separate math section will create apt clutter

**Comment by asdfugil** [comment]
Hayden said that

**Comment by Cryptiiiic** [comment]
ah cool

**Pull request merged**
