### PR TITLE
Add emacs

### PR DESCRIPTION
**Pull request by TheRealKeto**
This PR adds GNU ``emacs``, the self-documenting text editor. Unfinished, but I can't do much on my end anymore, so I'm hoping contributions from others make it possible to add it to Procursus.

### CODE REVIEW

**Comment by Gymxo** [comment]
the emac options can be changed as needed

**Comment by CRKatri** [comment]
What is keeping this as a draft?

**Comment by TheRealKeto** [comment]
> What is keeping this as a draft?

The Makefile's dirty; Hayden agrees with that, and Natalie (aka Gymxo) was meant to take care of that, in this PR or in another

AFAIK, Natalie was able to compile this specific version.

**Comment by CRKatri** [comment]
Is Natalie still working on it from this branch or a different branch? Should I close this?

**Comment by TheRealKeto** [comment]
Ask Natalie. It was being worked on, but I never bothered to ask.

**Pull request closed without merging**
