### PR TITLE
Xorg-server

### PR DESCRIPTION
**Pull request by Gymxo**

### CODE REVIEW

**Comment by CRKatri** [comment]
Is this use able? or still WIP.

**Comment by Gymxo** [comment]
> Is this use able or still WIP?

Yes this works

**Comment by CRKatri** [comment]
Over VNC, or can it drive the display?

**Comment by asdfugil** [comment]
afaik it can't use the framebuffer (yet)

**Comment by Gymxo** [comment]
The TigerVnc to which currently isn't accepted yet has Xvnc to which can create virtual displays that can be viewed over vnc viewers. However, Xnest and Xephyr still work when doing export DISPLAY and can be used to display apps. The reason why Xorg and Xdmx got added is that I was told by Hayden to add them(even if they don't work properly atm).

**Pull request merged**
