### PR TITLE
all da targets

### PR DESCRIPTION
**Pull request by asdfugil**
- bridgeOS
- audioOS
- arm64e

### CODE REVIEW

**Comment by Diatrus** [comment]
I don’t want audioOS or bridgeOS targets. They aren’t useful.

**Comment by asdfugil** [comment]
bridgeOS I get it, but how about audioOS?

**Comment by asdfugil** [comment]
you could very much use it a HomePod as a server.
It is practically always powered on and connected to internet.
and it has reasonable storage for that purpose

**Comment by Diatrus** [comment]
> you could very much use it a HomePod as a server.
> It is practically always powered on and connected to internet.
> and it has reasonable storage for that purpose

I don't think it has nearly enough storage for a valid server. IIRC the storage couldn't even handle a full bootstrap.

**Comment by asdfugil** [comment]
Well, it has 16 GB  storage and we can probably use up to 8 GB.

**Comment by Diatrus** [comment]
That's alright to me, then.

**Pull request merged**
