### PR TITLE
keyrings: Remove stkc-keyring

### PR DESCRIPTION
**Pull request by TheRealKeto**
We do not need this malware!

### CODE REVIEW

**Comment by stekc** [comment]
:trollface:

**Comment by asdfugil** [comment]
how is this malware

**Comment by TheRealKeto** [comment]
Unknown 1s and 0s for a dead repository.

**Review by asdfugil — CHANGES_REQUESTED** [review]
nah it is not unknown

**Review by CRKatri — APPROVED** [review]

**Pull request merged**
