### PR TITLE
add dtrace

### PR DESCRIPTION
**Pull request by asdfugil**
What @cameren2k wanted.

### All Submissions

* [x] Have you made sure there aren't any other open [Pull Requests](https://github.com/ProcursusTeam/Procursus/pulls) for the same update/change?
* [ ] This Pull Request doesn't contain any package additions; it's a small change (e.g README change)

### Package Additions/Updates

* [x] Have you confirmed this builds & works as intended on an iOS device (if applicable)?
* [ ] Have you confirmed this builds & works as intended on a macOS device (if applicable)?

Note: Before this is merged, when building this with an existing build_base, `$(BUILD_BASE)$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/include/sys/proc.h` must be deleted as the one from MacOSX.sdk is missing some definitions.

### CODE REVIEW

**Comment by Torrekie** [comment]
libproc requires `CSArchitecture` which was not defined in the CoreSymbolication.h you've used, but found a typedef in [this one](https://github.com/ashikase/libsymbolicate/blob/master/include/CoreSymbolication.h)

```
typedef struct _CSArchitecture {
    cpu_type_t cpu_type;
    cpu_subtype_t cpu_subtype;
} CSArchitecture;
```

**Comment by asdfugil** [comment]
A system may be able to run binaries different architecure from the dtrace binary's architecture. For example: arm64e and arm64

**Comment by Torrekie** [comment]
yes that's the issue, then I have found another typedef for `CSArchitecture` [here](https://git.progress-linux.org/packages/engywuck-backports/thunderbird/tree/widget/cocoa/nsCocoaDebugUtils.h?id=9529565cb94cc84694250fa8a91d1bf94cff2b73) that do `typedef unsigned long long CSArchitecture`. Could *probably* be a fix for that, `kCSArchitectureArm64_32` and `kCSArchitectureArm64` should be some constants like
```
#define kCSArchitectureArm64 0x10100000c
#define kCSArchitectureArm64_32 0x200000c
```

**Comment by Torrekie** [comment]
After reversing the shipped libdtrace.dylib in macOS dsc, I'm now quite sure how `kCSArchitectureArm64` and `kCSArchitectureArm64_32` was defined:
```
#define kCSArchitectureArm64 0x100000c
#define kCSArchitectureArm64_32 0x200000c
```

**Comment by Torrekie** [comment]
No, I checked the return value of `CSArchitectureGetArchitectureForName()` again, it returns `4311744524` (0x10100000c in hex), does not cater to what we needed for constant `kCSArchitectureArm64`, it should not contain cpu subtypes.
```
TorrekiedeMBP:~ torrekie$ cat test.c 
#include <stdio.h>
extern unsigned long long CSArchitectureGetArchitectureForName(char *);

int main() {
  printf("%llu\n", CSArchitectureGetArchitectureForName("arm64"));
}
TorrekiedeMBP:~ torrekie$ cc test.c -framework CoreSymbolication -F /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks
TorrekiedeMBP:~ torrekie$ ./a.out 
4311744524
```

**Comment by CRKatri** [comment]
Why did you close all of your PRs?

**Pull request closed without merging**
