### PR TITLE
Fixes tihmstar project configure versioning

### LINKED ISSUE #626: xpwn base is the wrong path
Because the path is wrong, the libs and headers are being stored nested in one more xpwn dir.

### PR DESCRIPTION
**Pull request by Cryptiiiic**
Fixes tihmstar project configure versioning

### CODE REVIEW

**Comment by Diatrus** [comment]
Don’t change the xpwn includes path.

**Comment by Cryptiiiic** [comment]
> Don’t change the xpwn includes path.

does 69c494b look good for this? @Diatrus

**Comment by Diatrus** [comment]
Better. Putting on hold for discussion, as @1Conan had another idea for doing this.

**Comment by Cryptiiiic** [comment]
I have local changes for versioning that I will push soon, its all sed patches for tihmstar configure projects @Diatrus

**Comment by Cryptiiiic** [comment]
I've done all I can think of for the time being, unless there is more for xpwn.

**Comment by Cryptiiiic** [comment]
Undid xpwn, removed comments

**Pull request merged**
