### PR TITLE
add libbluray

### PR DESCRIPTION
**Pull request by asdfugil**
works fine on darwin-amd64

### CODE REVIEW

**Comment by asdfugil** [comment]
i should make this not build for iOS

**Comment by asdfugil** [comment]
all right this should be fine now

**Comment by CRKatri** [comment]
Why is this disabled on iOS?

**Comment by sunflsks** [comment]
Because it requires DiskArbitration.framework, which is only available on macOS.

**Comment by CRKatri** [comment]
Oh ok.

**Comment by TheRealKeto** [comment]
Rebase/merge with main again and move your Makefile to the ``makefile`` directory.

**Pull request closed without merging**
