### PR TITLE
Update uikittools to 2.0.6

### PR DESCRIPTION
**Pull request by m1stadev**

### CODE REVIEW

**Comment by CRKatri** [comment]
`2.0.5` doesn't have `deviceinfo`, that's coming in `2.0.6`, along with fast `uicache -a`

**Comment by m1stadev** [comment]
ah, in that case then i'll just hold off on updating entirely until 2.0.6 since I don't believe there's anything *huge* that's been added since the last time it's been updated

**Comment by CRKatri** [comment]
`2.0.5` only added manpages.

**Comment by CRKatri** [comment]
Also, can you merge https://github.com/ProcursusTeam/Procursus/tree/ck/uikittools-update into this?

**Pull request closed without merging**
