### PR TITLE
add chntpw

### PR DESCRIPTION
**Pull request by asdfugil**

### CODE REVIEW

**Comment by asdfugil** [comment]
doesn't build for iOS but i don't care because it is useless there.

**Comment by CRKatri** [comment]
You may not care but iOS is a primary target.

**Comment by sunflsks** [comment]
This builds fine for me for iOS. However, I don't run FreeBSD. Could you post the errors?

**Comment by asdfugil** [comment]
actually i build this on macOS

**Comment by asdfugil** [comment]
> This builds fine for me for iOS. However, I'm building on macOS so that might be a contributing factor. Could you post the errors?

```

/Users/nick/Procursus/build_base/iphoneos-arm64/1700//usr/include/stdlib.hchar    *getenv(const char *);
                           ^
:167:39/Users/nick/Procursus/build_base/iphoneos-arm64/1700//usr/include/stdlib.h:181:5: /Users/nick/Procursus/build_base/iphoneos-arm64/1700//usr/include/stdlib.h:147:25: note: : warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]error: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]

insert '_Nullable' if the pointer may be nulllong     strtol(const char *__str, char **__endptr, int __base);
                                         ^#if TARGET_OS_IPHONE


    ^
char    *getenv(const char *);
```

**Comment by asdfugil** [comment]
> This builds fine for me for iOS. However, I'm building on macOS so that might be a contributing factor. Could you post the errors?

TARGET_OS_IPHONE is not defined
```
/Users/nick/Procursus/build_base/iphoneos-arm64/1700//usr/include/stdlib.hchar    *getenv(const char *);
                           ^
:167:39/Users/nick/Procursus/build_base/iphoneos-arm64/1700//usr/include/stdlib.h:181:5: /Users/nick/Procursus/build_base/iphoneos-arm64/1700//usr/include/stdlib.h:147:25: note: : warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]error: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]

insert '_Nullable' if the pointer may be nulllong     strtol(const char *__str, char **__endptr, int __base);
                                         ^#if TARGET_OS_IPHONE
                                         ```

**Comment by asdfugil** [comment]
fixed @CRKatri

**Comment by sunflsks** [comment]
lgtm

**Pull request merged**
