### PR TITLE
Add aptitude

### PR DESCRIPTION
**Pull request by CRKatri**
~~#161 must be merged before~~

### CODE REVIEW

**Comment by Diatrus** [comment]
Is this nearly ready?

**Comment by CRKatri** [comment]
Should be ready this week or early next week, haven't had much time to work on it since opening this draft.

**Review by Diatrus — CHANGES_REQUESTED** [review]
```configure: error: in /Users/haydenseay/GitHub/Procursus/build_work/iphoneos-arm64/1600/aptitude:
configure: error: C compiler cannot create executables
See 'config.log' for more details
gmake[1]: *** [aptitude.mk:20: aptitude] Error 77
```

**Comment by CRKatri** [comment]
Please send me the `config.log` so that I can try and fix this as it compiles fine for me on both MacOS and Linux.

**Pull request merged**
