### PR TITLE
Fix libpng.pc, use GNU chown to avoid base-package issues on Big Sur, update build requirements in README.md

### PR DESCRIPTION
**Pull request by deatondg**
This PR includes the following changes:
- Patches libpng.pc.in to use Apple’s zlib instead of looking for zlib.pc (fixes issue #289)
- Bumps the deb version of libpng16
- Uses GNU chown to build base-package on macOS when present
- Update the build-deps in the README

### CODE REVIEW

**Comment by Diatrus** [comment]
Why is GNU chown needed on Big Sur?

**Comment by CRKatri** [comment]
Also, python 3.8 is no longer a dependency, we now need python 3.9.

**Comment by deatondg** [comment]
@Diatrus On my system (which is an almost entirely clean Big Sur except for these build dependencies), running `$(FAKEROOT) $(CHOWN) 0:3 $(BUILD_DIST)/base/var/empty` or similar commands results in a permissions error. Switching to GNU’s chown doesn’t have this problem. It’s possible something other than Big Sur causes this, although this worked fine on my old Catalina setup without using GNU chown.

@CRKatri I’ll fix that tomorrow morning.

**Comment by Diatrus** [comment]
@deatondg have you possibly not disabled SIP? fakeroot does not function properly if SIP is enabled on Catalina+. You can test by running `fakeroot whoami`.

**Comment by deatondg** [comment]
@Diatrus Lol... I totally forgot to disable SIP on this install, that’s the problem. Excuse my lack of thought, I’ll revert that commit.

**Comment by Diatrus** [comment]
Thank you tons for your contribution. It's much appreciated, I hope to keep seeing more. 👍

**Pull request merged**
