### PR TITLE
Add pacman and libalpm

### PR DESCRIPTION
**Pull request by CRKatri**

### CODE REVIEW

**Comment by Diatrus** [comment]
Can you explain where pacman would come in use on the repo?

**Comment by CRKatri** [comment]
Pacman is required to use `makepkg`.

**Comment by Diatrus** [comment]
Ah. I presume makepkg is included in pacman?

**Comment by CRKatri** [comment]
Yes.

**Comment by Diatrus** [comment]
Could you do me a favor and rename pacman's package to makepkg? I want it to be clear that this is a utility for arch users rather than an apt-alternative.

**Pull request merged**
