### PR TITLE
Add Mightnight commander to procursus 

### PR DESCRIPTION
**Pull request by Gymxo**

### CODE REVIEW

**Comment by Diatrus** [comment]
Epic

**Comment by Diatrus** [comment]
Reminder for me later: deb deps are wrong compared to build deps.

**Comment by Gymxo** [comment]
fixed

**Comment by CRKatri** [comment]
the correct dep is `gettext` not `libitnl`

**Comment by CRKatri** [comment]
The build-dep is `gettext` the package dep is `libintl8`.

**Comment by Gymxo** [comment]
Hopefully nothing else needs fixing

**Pull request merged**
