### PR TITLE
Add python3-psutil

### PR DESCRIPTION
**Pull request by DaOfficialRolex**
I am guessing iOS will need some patches to build correctly. For the time being this will be a draft. This is where the code fails when building for iOS.

```
building 'psutil._psutil_osx' extension
creating build/temp.macosx-11.0-x86_64-3.9
creating build/temp.macosx-11.0-x86_64-3.9/psutil
creating build/temp.macosx-11.0-x86_64-3.9/psutil/arch
creating build/temp.macosx-11.0-x86_64-3.9/psutil/arch/osx
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=11.0 -isystem /Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/include -isystem /Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/include -F/Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/System/Library/Frameworks -F/Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/Library/Frameworks -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=11.0 -isystem /Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/include -isystem /Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/include -F/Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/System/Library/Frameworks -F/Users/haydenseay/GitHub/Procursus/build_base/darwin-amd64/1700//opt/procursus/Library/Frameworks -O2 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -miphoneos-version-min=14.0 -isystem /Users/rolex/Procursus/build_base/iphoneos-arm64/1700/usr/include -isystem /Users/rolex/Procursus/build_base/iphoneos-arm64/1700/usr/local/include -F/Users/rolex/Procursus/build_base/iphoneos-arm64/1700/System/Library/Frameworks -F/Users/rolex/Procursus/build_base/iphoneos-arm64/1700/Library/Frameworks -O2 -arch arm64 -miphoneos-version-min=14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -isystem /Users/rolex/Procursus/build_base/iphoneos-arm64/1700/usr/include -isystem /Users/rolex/Procursus/build_base/iphoneos-arm64/1700/usr/local/include -Wno-error-implicit-function-declaration -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_OSX=1 -I/opt/procursus/include/python3.9 -c psutil/_psutil_common.c -o build/temp.macosx-11.0-x86_64-3.9/psutil/_psutil_common.o
clang: error: invalid argument '-mmacosx-version-min=11.0' not allowed with '-miphoneos-version-min=14.0'
clang: warning: using sysroot for 'iPhoneOS' but targeting 'MacOSX' [-Wincompatible-sysroot]
clang: error: invalid argument '-mmacosx-version-min=11.0' not allowed with '-miphoneos-version-min=14.0'
clang: warning: using sysroot for 'iPhoneOS' but targeting 'MacOSX' [-Wincompatible-sysroot]
error: command '/usr/bin/cc' failed with exit code 1
gmake[1]: *** [python-psutil.mk:18: python-psutil] Error 1
gmake: *** [Makefile:749: rebuild-python-psutil-package] Error 2

```

### CODE REVIEW

**Review by Cryptiiiic — COMMENTED** [review]
Although extremely hacky, it actually builds into a deb for iOS now.

**Comment by DaOfficialRolex** [comment]
> Although extremely hacky, it actually builds into a deb for iOS now.

I am seriously impressed either way. Thank you for the help!

**Comment by CRKatri** [comment]
Remove python3.9 dep, it should not require a specific point release.

**Comment by Cryptiiiic** [comment]
I'm gonna mark this as ready for review now.

**Review by Cryptiiiic — APPROVED** [review]
Seems ready for merging now :)

**Pull request merged**
