### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by captinc**

### CODE REVIEW

**Review by DaOfficialRolex — APPROVED** [review]
THIS IS THE MOST IMPORTANT CHANGE THAT WE HAVE EVER NEEDED IN PROCURSUS LIFETIME!!!!!!

**Comment by captinc** [comment]
No need to thank me!

**Comment by brennanleblanc0** [comment]
Somebody give this guy an award or something

**Comment by 1Conan** [comment]
This is way too good to be merged. I need to pay @captinc first.

**Pull request merged**
