### PR TITLE
no need for brew

### PR DESCRIPTION
**Pull request by asdfugil**
delete brew from readme

### CODE REVIEW

**Comment by Gymxo** [comment]
Don’t you think this title could be a little bit more appropriate?

**Comment by asdfugil** [comment]
All right

**Comment by m1stadev** [comment]
Putting this off until the Procursus bootstrap for macOS is fully finished.

**Comment by Diatrus** [comment]
@m1stadev no need to holdoff since, on as2, Procursus is required. Also @absidue you maayyyy be missing a couple depends on that apt install statement. Test from a fresh install? :)

**Comment by m1stadev** [comment]
Procursus is required for as2, but the Procursus boostrap isn't easily installable for users yet.

**Comment by Diatrus** [comment]
@m1stadev that’s why the readme is updated only on as2.

**Comment by asdfugil** [comment]
tested on a fresh install to work.

**Comment by Diatrus** [comment]
Obsolete

**Pull request closed without merging**
