### PR TITLE
macOS 12 (1800) support

### PR DESCRIPTION
**Pull request by asdfugil**
- this adds support for compiling for 1800
- darwin-amd64 compiles and the binaries runs
- thread_state.h should not be downloaded on 1800

### CODE REVIEW

**Comment by asdfugil** [comment]
This is darwin-amd64/1800
https://cdn.discordapp.com/attachments/781041045760770049/851844752974282823/boostrap_1800_darwin-amd64.tar.zst

**Comment by Diatrus** [comment]
@asdfugil is thread_state included in the sdk or something?

**Comment by asdfugil** [comment]
> @asdfugil is thread_state included in the sdk or something?

It is. And the one downloaded has some symbols missing.

**Comment by Diatrus** [comment]
@asdfugil what symbols?

**Comment by asdfugil** [comment]
> @asdfugil what symbols?

`THREAD_STATE_MAX`
this causes problems with lz4 which is a `STRAPPROJECT`

**Comment by asdfugil** [comment]
Also this is darwin-arm64 (not tested because no m1)

https://cdn.discordapp.com/attachments/781041045760770049/851956096486604851/bootstrap_1800_darwin-arm64.tar.zst

**Comment by asdfugil** [comment]
don't merge this 
This breaks <1800

**Comment by asdfugil** [comment]
This is fixed.

**Pull request merged**
