### PR TITLE
Enable UTF8 support in nano + Fix reading system config from /etc/nanorc

### PR DESCRIPTION
**Pull request by marijuanARM**

### CODE REVIEW

**Comment by Diatrus** [comment]
Does enabling utf8 create a new dependency for nano that you didn't account for here?

**Comment by marijuanARM** [comment]
Just tried with no other packages compiled, doesn't look like it does.

**Comment by marijuanARM** [comment]
Also noticed from reading through nano documentation, looks like nano will read the system nanorc from /usr/bin/etc/nanorc, so a symlink might be needed
Relevant

**Comment by Diatrus** [comment]
Did you test this on device? If not, can you? If so, did it read from /etc/nanorc properly?

**Comment by marijuanARM** [comment]
Yup, reads from /etc/nanorc perfectly (and made sure that it wasn't just a ~/.nanorc being read that made me think it was reading /etc/nanorc).

**Pull request merged**
