### PR TITLE
libkernrw: Fix control typo

### PR DESCRIPTION
**Pull request by TheRealKeto**
Surprisingly, it wasn't @CRKatri this time...

### CODE REVIEW

**Comment by CRKatri** [comment]
Haha, looks like @Diatrus’s changes need better review too.

**Comment by Diatrus** [comment]
Shhh

**Comment by Diatrus** [comment]
No need to bump ver num. we can just push a silent update to fix the section.

**Comment by TheRealKeto** [comment]
Reverted the change with the latest commit.

**Review by m1stadev — APPROVED** [review]
LGTM

**Pull request merged**
